# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0004_auto_20170813_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_img', models.CharField(max_length=150, verbose_name='Titulo da Imagem:')),
                ('imagem', models.ImageField(upload_to='imagens/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
        migrations.AddField(
            model_name='imagenspost',
            name='post_imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associacao.Post'),
        ),
    ]
