# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0005_auto_20170814_2239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagensPost',
            new_name='ImagenDoPost',
        ),
    ]
