# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 04:55
from __future__ import unicode_literals

import associacao.models
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0006_auto_20170814_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideDoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_slide', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to=associacao.models.get_file_path)),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('url_slide', models.CharField(default='#', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='imagendopost',
            options={'verbose_name': 'Imagem do Post', 'verbose_name_plural': 'Imagens do Post'},
        ),
        migrations.AlterField(
            model_name='imagendopost',
            name='imagem',
            field=models.ImageField(upload_to=associacao.models.get_file_path),
        ),
    ]
