# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0007_auto_20170815_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagendopost',
            name='imagem',
            field=models.ImageField(upload_to='imagens/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='slidedosite',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '2000x700', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='slidedosite',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
