# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0008_auto_20170816_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidedosite',
            options={'verbose_name': 'Slide do Site', 'verbose_name_plural': 'Slides do Site'},
        ),
        migrations.AlterField(
            model_name='slidedosite',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '2000x700', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='slidedosite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
