# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0009_auto_20170820_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidedosite',
            name='url_slide',
            field=models.CharField(max_length=255),
        ),
    ]
