# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0010_auto_20170820_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedosite',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slidedosite',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidedosite',
            name='status',
            field=models.CharField(choices=[('0', 'Offiline'), ('1', 'Online')], default='0', max_length=1),
        ),
    ]
